name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Sync LeetCode
        uses: anishLearnsToCode/leetcode-sync@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.CSRF_TOKEN }}
          destination-folder: leetcode
          verbose: true
